#!/bin/bash
ENV_DIR="./env"

if [ ! -d "$ENV_DIR" ]; then
  echo "Creating virtual environment..."
  python3 -m venv "$ENV_DIR"
  source "$ENV_DIR/bin/activate"
  pip install --prefer-binary -r requirements.txt

else
  source "$ENV_DIR/bin/activate"
fi

exec "$@"  # Run whatever the user passes

